### ISSUE TITLE
Nice Work

### ISSUE THREAD

**Issue by danbucholtz** [ihadeed/charttest#2]
Hey,

Nice work here.  Just wanted to say thanks, and thanks for your great work with Ionic Native, too.  I tried to find you on Twitter but to no avail.

Thanks,
Dan

**Comment by ihadeed** [comment]
Hey @danbucholtz 

Thanks for your kind message. I love helping with Ionic Native, can't wait to get some free time soon to get back to it.

I'm not on Twitter at the moment, but I might be joining sometime soon!
