### ISSUE TITLE
Can you tell why it isnt working anymore?

### ISSUE THREAD

**Issue by Simsal** [ihadeed/charttest#3]
Hey there,

just stumbled over your demo App.

Can you tell me, why the App isn't working anymore?
Problem with versions?

Greetings

**Comment by ihadeed** [comment]
Yeah looks like it's problem with versions. 
I didn't bother to look into the reasons since ChartJS 2.0 is out. I'm working on something here: https://github.com/ihadeed/ng2-chartjs2

**Comment by Simsal** [comment]
Thx for the answer.

Looking forward to your new work.
